services: 
    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=mysecretpassword
      ports:
      - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 10s
        timeout: 5s
        retries: 5

    app:
      depends_on:
        db:
          condition: service_healthy
      build: ./backend
      restart: unless-stopped
      environment:
        - PORT=3000
        - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/postgres?schema=public
      stdin_open: true
      tty: true
      ports:
      - "3000:3000"

    web:
      depends_on:
        - app
      build: ./frontend
      restart: unless-stopped
      stdin_open: true
      tty: true
      ports:
      - "8080:8080"

volumes:
  db: